# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Rowan MemSat'
tagline:          ''
description:      'A portal for all things MemSat.'
#url:              'http://localhost:4000'
#baseurl:          ''
url:              'memsat.space'
baseurl:          ''

# Navigation
navigation:
- text: About MemSat
  url: /about/
- text: Launch
  url: /launch/
- text: Updates
  url: /updates/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Christopher Frederickson'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       ''
flickr:
github:         ''
gplus:          ''
instagram:
pinterest:
linkedin:       ''
rss:
stackoverflow:  ''
twitter:        ''

# Google Analytics
gahandler: ''

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'false'

# Disqus
disqushandler: ''

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/updates/page:num'
destination: ./_site

# Custom vars
version:          0.1
